name: participium-release

services:
  api:
    image: giova21/participium-api:latest
    container_name: participium-api
    restart: always
    depends_on:
      - postgres
      - minio
    environment:
      PORT: 5000
      FRONTEND_URL: http://localhost:5173
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-participium}
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_PUBLIC_ENDPOINT: localhost
      MINIO_PUBLIC_PORT: 9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
      MINIO_BUCKET_NAME: participium-reports
      MINIO_USE_SSL: 'false'
    ports:
      - '5000:5000'
    networks:
      - participium-net

  web:
    image: giova21/participium-web:latest
    container_name: participium-web
    restart: always
    ports:
      - '5173:80'
    depends_on:
      - api
    networks:
      - participium-net

  postgres:
    image: postgis/postgis:18-3.6
    platform: linux/amd64
    container_name: participium-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-participium}
    volumes:
      - participium_pg_data:/var/lib/postgresql
    networks:
      - participium-net

  minio:
    image: minio/minio:latest
    container_name: participium-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - participium_minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - participium-net
    ports:
      - '9001:9001'
      - '9000:9000'

volumes:
  participium_pg_data:
    name: participium_release_pg_data
  participium_minio_data:
    name: participium_release_minio_data

networks:
  participium-net:
    driver: bridge